### ISSUE TITLE
February Community Outreach

### ISSUE THREAD

**Issue by TisVictress** [paketo-buildpacks/community#126]
While this month's driver (assignee) should help start this conversation and/or identify a domain to focus on, this should be a team effort. The goal is a deliverable that will help grow the Paketo community and continue to improve communication and the sharing of ideas.
Some example deliverables include (but are not limited to):
* blog posts
* a conference proposal
* virtual demos
* a presentation at a tech meetup

**Comment by sophiewigmore** [comment]
https://www.youtube.com/watch?v=GDInFocQJTU by @ryanmoran
