### ISSUE TITLE
Consider pinning this repo and/or adding detailed governance/contributor info on paketo.io

### ISSUE THREAD

**Issue by andymoe** [paketo-buildpacks/community#14]
## What were you attempting to do?
I was attempting to learn how to get involved in and contribute to the Paketo Buildpack community.
 
## What did you expect to happen?
I expected to be able to quickly find best practices for interacting with the paketo buildpacks community so I could easily begin to contribute.

## What was the actual behavior?
I visited https://paketo.io and as I scrolled down the website I saw callouts under the "Why Paketo Buildpacks" section saying that these Buildpacks are Secure, Standardized and Community-Driven. 

I hoped to find out more about what the community driven process was so I could contribute but since I saw no links to more details I kept scrolling. I then saw the "Get Started" link at the bottom of the page and clicked it.

From there I read the "Getting Started" section, and then checked out the sample apps on the github page. I then went back to  the paketo docs site and looked for more contributing guidelines but did not find any.

After this I went back to the landing page of the Paketo site and clicked the link to github and saw the pinned repos and visited the Go Paketo Buildpack repo. Unfortunately I saw no CONTRIBUTOR.md or anything similar.

Went back to the main https://github.com/paketo-buildpacks page and started scrolling down through the 96 repositories when I eventually came upon this community repo and by chance clicked on it.

Inside I finally found a link to https://github.com/paketo-buildpacks/community/blob/main/GOVERNANCE.md which was cool but I was disappointed to find a "Coming soon!" under the Roadmap section.

I think it would be great if this repo was either pinned to the paketo github landing page or perhaps a section with details on governance and contributing could be added to the Paketo Website or Paketo docs website.

## Checklist
* [x ] I have included steps for reproduction.

**Comment by fg-j** [comment]
This seems related to this issue: https://github.com/paketo-buildpacks/paketo-website/issues/21

**Comment by kvedurmu** [comment]
I'm going to close this out as the PR referenced by @fg-j should cover this. Feel free to open back up if you have any other suggestions.
