### ISSUE TITLE
TEAMS.md is outdated

### ISSUE THREAD

**Issue by thitch97** [paketo-buildpacks/community#3]
**Context**
Our organization has changed a bit in the past few months as new subteams have been created and new contributors have joined various subteams.

**Proposal**
The TEAMS.md document should be updated to include the following:
**Ruby**: rmoran, swigmore
**Builders**: fg-j, dumez-k, ekcasey
**Stacks**: dumez-k, mdelillo, martyspiewak

**Comment by ForestEckhardt** [comment]
Resolved by #7
