### ISSUE TITLE
Add links to teams in TEAMS.md

### ISSUE THREAD

**Issue by robdimsdale** [paketo-buildpacks/community#71]
I would like to propose that we add links to the teams described in [TEAMS.md](https://github.com/paketo-buildpacks/community/blob/main/TEAMS.md). For example, the builders maintainer team would link to: https://github.com/orgs/paketo-buildpacks/teams/builders-maintainers and the builders contributor team would link to https://github.com/orgs/paketo-buildpacks/teams/builders-contributors.

I think this will aid in discovery of the github pages for the teams, which will facilitate discovery of any additional conversations or activity associated with the teams.

I am happy to implement this but I wanted to see if there was any reason we hadn't already done this.

**Comment by ryanmoran** [comment]
I think the biggest reason we'd never added this is that it appears the links to these team pages aren't public. I can't really figure out what level of permissions one would need to see these pages since I'm an admin for the whole org.
