### ISSUE TITLE
No reference to Getting Started guide from README

### ISSUE THREAD

**Issue by davidmirror-ops** [paketo-buildpacks/community#82]
## What happened?
None of the Paketo Buildpacks repo README pages provide a reference to the Getting Started guides. 

* What did you expect to happen?
A step-by-step guide on how to start using the Buildpack would be a great addition to the current content. Also, consider using visuals (GIFs, screenshots, etc) to quickly communicate how the Buildpack is used.
If README is the landing page for the repo, for a new user it would be helpful to find:

a. How to get started?
b. Why?
c. What's inside this Buildpack?
d. Where to learn more?

* What was the actual behavior? Please provide log output, if possible.
Right now, Buildpacks README pages are mainly focused on the contents (the what) of the Buildpack and what it does. It provides references to the samples dir and the docs but it's not clear on how to get started quickly

* Prior art

Curated list of interesting README pages from different projects: https://github.com/matiassingers/awesome-readme

**Comment by fg-j** [comment]
Given that Paketo manages approximately 100 individual buildpack repositories, maybe it's more maintainable to write 1 README that's a prefix or suffix for all/most Paketo repo READMEs. For instance

```markdown
# Name of the Buildpack
<Maintainer-supplied content that's specific to this buildpack, including what's inside this buildpack>

<!--- Below, content that's centrally managed and synced with each repo  --->
## Why buildpacks?

## Where to learn more?

## How to contribute?
```

**Comment by dmikusa-pivotal** [comment]
I think we've had conversations about this in the past, essentially what is the purpose of the README.md for a buildpack. I don't remember if we had come to an agreement, but I think we were talking at one point at least about using the README as a reference guide.

I recall at one point there being a tool discussed to convert the README into the reference section for our docs, so there is not duplicate sources of information to keep in sync.

I think we could do a better job of redirecting users to the docs though. Perhaps we could add something to the top of the README like "If you are a user of buildpacks, we strongly recommend going to the documentation which is the central repository for knowledge on Paketo buildpacks".

I know I've seen similar things in README's before. "If you're a user, go here. If you're a developer, go here" Stuff like that to point people to the right spot. That could help reduce the duplication of information and the proliferation of locations users feel like they need to look for information.

**Comment by ForestEckhardt** [comment]
There is [an RFC](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0040-auto-reference-docs.md) centered around using READMEs as the source for all reference documentation.

**Comment by davidmirror-ops** [comment]
@ForestEckhardt the ideas in that RFC are amazing. I believe that when complemented with the most generic "How to get started with buildpacks" at the README template would help a lot!

If users need more details then we can redirect them to docs as @dmikusa-pivotal suggested.

**Comment by davidmirror-ops** [comment]
https://github.com/paketo-buildpacks/.github/pull/23 implemented a reference to the **Getting started** page from base README
