### ISSUE TITLE
Issue template designed just for bug reports

### ISSUE THREAD

**Issue by davidmirror-ops** [paketo-buildpacks/community#83]
## What happened?
When opening a new issue for some of the Buildpacks, the resulting Issue template asks mainly for bug report related information, which is not relevant if the Issue has a different goal

* What did you expect to happen?

There should be options for users filing Issues (and corresponding templates should be present), especially if they are trying to:

1. Submit a Feature Request
2. Report a security vulnerability

There are repos like /paketo-wesbite with several options available, but that's not the case for most of the buildpacks repos.

**Comment by dmikusa-pivotal** [comment]
+1 for this. It annoys me every time I open an issue.  I also think we ask too many questions, which I think could possibly make people just go away. 

I believe that's being set project-wide here -> https://github.com/paketo-buildpacks/.github. We should probably do the same for https://github.com/paketo-community, which I don't think has a `.github` project.

@davidmirror-ops Do you have any recommendations for what scenarios we should cover beyond the three above?

I can write up an RFC. I suspect we'd want to get sign-off from teams before changing the templates.

**Comment by davidmirror-ops** [comment]
Thanks @dmikusa-pivotal!

I think those three scenarios would be a good starting point for the most common requests (unless a different trend is detected in the future)

BTW I'm creating most of the Issues under the /community repo but it refers to project-wide reccomendations.

**Comment by fg-j** [comment]
This is done! We now have org-wide issue templates. Check out https://github.com/paketo-buildpacks/go-build/issues/new/choose for an example.
