### ISSUE TITLE
Relabel and expand project meetings

### ISSUE THREAD

**Issue by davidmirror-ops** [paketo-buildpacks/community#88]
Currently, there are two public Paketo Buildpacks meetings: Working Group and Java Buildpacks.

The Working Group meeting seems to be designed mainly for contributors interested on discussing RFCs and project-wide updates or initiatives.

Judging by async interactions on Slack and Github, most of them come from users with questions on how to use/adapt an existing buildpack, not necessarily how to build a new one.

* What did you expect to happen?
In order to have dedicated and purpose-built synchronous paths of communication for this community, a couple of initiatives are proposed:

1. Rename Working Group Meeting to 'Contributors Meeting'. The term 'Working Group' could be not clear enough for new users. The current agenda could remain the same (RFC Discussion, Upstream project updates, etc)
2. Establish a new 'User Meeting' with an initial monthly cadence, specifically designed to:
a. Provide brief updates on ROADMAP execution status
b. Open the floor for users to bring questions, give demos and/or showcase what they are doing/not achieving right now with the project
c. A place to start or continue async conversations and also get to know a little better the community of Paketo users

Please let me know if this proposal would need a RFC

**Comment by fg-j** [comment]
@davidmirror-ops Can we put this on the agenda for the next working group meeting?

**Comment by davidmirror-ops** [comment]
Sure thing @fg-j!

**Comment by robdimsdale** [comment]
This sounds very reasonable to me; I'd be happy for us to try it and see if it increases user interaction.

I don't think it would need an RFC or any other process, but I defer to the steering committee for that.

**Comment by davidmirror-ops** [comment]
So far, there's no strong evidence that another meeting is needed and we keep investing on async communication channels and leaving space in the WG meeting for users to ask questions.

This idea could be revisited in the future if deemed necessary
