### ISSUE TITLE
Build a public adopters list

### ISSUE THREAD

**Issue by davidmirror-ops** [paketo-buildpacks/community#89]
Build a list of companies/organizations willing to publicly share how they are using Paketo Buildpacks. This list would be in an ADOPTERS.md file at the /community repo.

This could help others while exploring how the project is being used in the field.

* Prior art
Velero ADOPTERS list: https://github.com/vmware-tanzu/velero/blob/main/ADOPTERS.md

**Comment by ryanmoran** [comment]
The `ADOPTERS.md` file was added in https://github.com/paketo-buildpacks/community/pull/101. @davidmirror-ops, is this done?

**Comment by davidmirror-ops** [comment]
Hey @ryanmoran yes it is!
