### ISSUE TITLE
Achieve OpenSSF Best Practices passing badge

### ISSUE THREAD

**Issue by davidmirror-ops** [paketo-buildpacks/community#92]
The OpenSSF [Best Practices badge](https://github.com/coreinfrastructure/best-practices-badge#readme) is a program for OSS projects to show that they follow best practices in several areas including Quality, Analysis, Security, among others.

Currently, Paketo Buildpacks is 64% short of achieving passing grade.

It's necessary to complete the missing information in the [project's profile](https://bestpractices.coreinfrastructure.org/en/projects/5938) (providing evidence when it's required) to get the `passing` badge. This would give potential users/contributors the assurance that this project is developed and maintained following a baseline of best practices.

**Comment by dmikusa-pivotal** [comment]
This is cool. How do we get the profile updated? Is that something the steering committee needs to provide answers for?

**Comment by fg-j** [comment]
Yeah, some of the things that are "unmet" are definitely in place in the project right now. For example, all buildpack repos provide a build system capable of rebuilding the compiled artifacts.

**Comment by davidmirror-ops** [comment]
Correct @dmikusa-pivotal and @fg-j 

I'm pretty sure most of the 'Unmet' requirements are already in place, we only need to confirm and (in some cases) provide evidence so yeah, I can through it with someone from the team who can provide details for all these domains.

**Comment by davidmirror-ops** [comment]
Achieved!
https://bestpractices.coreinfrastructure.org/en/projects/5938
