### ISSUE TITLE
Conduct an User Research exercise

### ISSUE THREAD

**Issue by davidmirror-ops** [paketo-buildpacks/community#98]
In order to have actionable feedback, gathered using formal methods and with clear goals so it can be used to improve Paketo user documentation, training material and to help soften the learning curve for new users, an User Research exercise could be useful.

This would be a team effort and also would require us to define:

1. Target persona
2. How its going to be communicated
3. Sample size (how many users make for a representative portion of the whole community?)
4. Logistics (time, method, retribution)

More info: https://www.interaction-design.org/literature/topics/user-research#

**Comment by johnnyr0x** [comment]
Survey is in progress here: https://docs.google.com/document/d/1tJ8sc8Wyf3_Bol_rGWXpLP6VlVDmsnHaUFIjcDsxHLA/edit

**Comment by johnnyr0x** [comment]
Could I get one person to take this survey to give me some feedback before sending to the wider community?

Link to survey: https://forms.gle/Tymb6EZRuVpPThjt6

**Comment by ryanmoran** [comment]
I submitted a response. I found the survey to be clear and had an understandable progression from question to question. I also appreciated the "magic wand" question at the end.

**Comment by davidmirror-ops** [comment]
Results are summarized [here](https://docs.google.com/presentation/d/1j8qHRSPbHn1U_59oy011HKWeOch3CYwDBJNU3lA_OYA/edit?usp=sharing)

As a potential improvement for the future, we could leave it as a permanent way for users to provide feedback and receive swag in return
